global:
  scrape_interval:     2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: redis_exporter_targets
    scrape_interval: 2s
    static_configs:
      - targets:
        - redis://cache_1:6379
        - redis://cache_2:6379
        - redis://cache_3:6379
        - redis://cache_4:6379
        - redis://cache_5:6379
        - redis://cache_6:6379
        - redis://cache_7:6379
        - redis://cache_8:6379
                
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis_exporter:9121
  
  - job_name: redis-exporter
    static_configs:
      - targets: ['redis_exporter:9121']